Merge feature to main
rgerhand/html-parser pull request #1
Opened 2023-01-29 19:57 UTC by rgerhand

2023-01-29 21:26 UTC, ppiasek requested changes
Please read PEP8 about docstrings on each level and please adapt ones in your code. 
Also some comments in MySQL class are also applicable in SQLite.

Also, as there are differences in usage MySQL and SQLite, think how you can refactor it so it will be easier to use both classes the same way (think about it like you have some scripts using MySQL code and now you wat to use same script with SQLite one, but you only want to change the object).

2023-01-29 21:26 UTC, ppiasek commented on MySQLClass.py
> +            empty_string += columns_with_type + ','
Try to consider + string concatenation as antipattern, it is usually the least efficient way of joining strings and there are better ones as f'string, string join etc.

To be honest, I think it would be better to create list of strings and then join them with ","

2023-01-29 21:26 UTC, ppiasek commented on MySQLClass.py
> +        sql_formula = f'''CREATE TABLE {table_name} ({columns_with_type_without_last_char})'''
No need to use ''', just single one

2023-01-29 21:26 UTC, ppiasek commented on MySQLClass.py
> +        data_to_insert = list(input("Insert data: ").split(','))
Why input?

2023-01-29 21:26 UTC, ppiasek commented on MySQLClass.py
> +        without_last_char = string_with_data[:-1]
Same as in create table

2023-01-29 21:26 UTC, ppiasek commented on MySQLClass.py
> +        sql_formula = f'''INSERT INTO {table_name} ({columns}) VALUES ({without_last_char})'''
Same as in create table

2023-01-29 21:26 UTC, ppiasek commented on SQLiteClass.py
> +                INSERT INTO {table_name} ({columns}) VALUES ({data})'''
This should fit in single line.

2023-01-30 13:13 UTC, rgerhand commented on SQLiteClass.py
> +    def con(self):
Fixed

2023-01-30 18:13 UTC, rgerhand commented on MySQLClass.py
> +        sql_formula = f'''CREATE TABLE {table_name} ({columns_with_type_without_last_char})'''
Fixed

2023-01-30 18:14 UTC, rgerhand commented on MySQLClass.py
> +        sql_formula = f'''INSERT INTO {table_name} ({columns}) VALUES ({without_last_char})'''
Fixed

2023-01-30 18:15 UTC, rgerhand commented on MySQLClass.py
> +        without_last_char = string_with_data[:-1]
Fixed

2023-01-30 18:16 UTC, rgerhand commented on SQLiteClass.py
> +                INSERT INTO {table_name} ({columns}) VALUES ({data})'''
Fixed

2023-01-31 15:58 UTC, rgerhand commented on MySQLClass.py
> +    def login(self, **kwargs):
Fixed

2023-01-31 16:42 UTC, rgerhand commented on MySQLClass.py
> +        for key, value in kwargs.items():
Fixed

2023-02-01 17:17 UTC, rgerhand commented on MySQLClass.py
> +        sql_formula = f'''INSERT INTO {table_name} ({columns}) VALUES ({without_last_char})'''
Fixed

2023-02-08 11:02 UTC, ppiasek requested changes

2023-02-08 11:02 UTC, ppiasek commented on faker_generator.py
> +        list_with_names.append(names_without_mr_and_mrs)
Can't you just generate data without honorifics? 
Also strip doesn't work as you think:
https://docs.python.org/3/library/stdtypes.html#str.lstrip

2023-02-08 11:02 UTC, ppiasek commented on faker_generator.py
> +        list_with_addresses.append(item.replace("\n", ", "))
Same as the upper function.

2023-02-08 15:13 UTC, rgerhand commented on DataBaseHandler.py
> +    def login(self, **kwargs: dict) -> True:
Fixed

2023-02-08 15:26 UTC, rgerhand commented on faker_generator.py
> +def generate_name(numbers_of_data: int) -> list:
Fixed

2023-02-09 10:06 UTC, rgerhand commented on MySQLClass.py
>          without_last_char = string_with_data[:-1]
Fixed

2023-02-09 11:41 UTC, rgerhand commented on faker_generator.py
> +    split_names = names.split(',')
Fixed

2023-02-09 11:56 UTC, rgerhand commented on faker_generator.py
> +        list_with_names.append(names_without_mr_and_mrs)
Fixed

2023-02-09 11:56 UTC, rgerhand commented on faker_generator.py
> +        list_with_addresses.append(item.replace("\n", ", "))
Fixed

2023-02-09 12:52 UTC, rgerhand commented on SQLiteClass.py
>          columns = ','.join(args)
Refactor

2023-02-09 14:10 UTC, rgerhand commented on SQLiteClass.py
>          columns = ','.join(args)
Len() counts the number of arguments , then this value is sent to the database

2023-02-13 10:42 UTC, ppiasek approved these changes
ok

2023-02-13 10:44 UTC, merged